In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [4]:
df = df.drop(["ID", "Levy", "Model", "Drive wheels", "Doors", "Wheel"], axis=1)

In [5]:
df

,Price,Manufacturer,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Color,Airbags
0,13328,LEXUS,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,Silver,12
1,16621,CHEVROLET,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,Black,8
2,8467,HONDA,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Black,2
3,3607,FORD,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,White,0
4,11726,HONDA,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,MERCEDES-BENZ,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Silver,5
19233,15681,HYUNDAI,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Red,8
19234,26108,HYUNDAI,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Grey,4
19235,5331,CHEVROLET,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Black,4
19236,470,HYUNDAI,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,White,12

In [6]:
one_hot_encoding = ["Manufacturer", "Category", "Leather interior", "Fuel type", "Gear box type", "Color"]
scaling = ["Prod. year", "Engine volume", "Mileage", "Airbags"]

In [7]:
def process_engine_volume(x):
    x = float("".join([i for i in x if i.isdigit() or i == "."]))
    return x

df["Engine volume"] = df["Engine volume"].apply(process_engine_volume)

In [8]:
def process_mileage(x):
    x = float("".join([i for i in x if i.isdigit() or i == "."]))
    x = 10000 * round(x/10000)
    return x

df["Mileage"] = df["Mileage"].apply(process_mileage)

In [9]:
ohe_scaler = LabelEncoder()
minmax_scaler = MinMaxScaler()

In [10]:
for col in one_hot_encoding:
    df[col] = ohe_scaler.fit_transform(df[col])
    df[col] = minmax_scaler.fit_transform(np.array(df[col]).reshape(-1, 1))

In [11]:
df

,Price,Manufacturer,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Color,Airbags
0,13328,0.500000,2010,0.4,1.0,0.333333,3.5,190000,6.0,0.000000,0.800000,12
1,16621,0.125000,2011,0.4,0.0,0.833333,3.0,190000,6.0,0.666667,0.066667,8
2,8467,0.328125,2006,0.3,0.0,0.833333,1.3,200000,4.0,1.000000,0.066667,2
3,3607,0.250000,2011,0.4,1.0,0.333333,2.5,170000,4.0,0.000000,0.933333,0
4,11726,0.328125,2014,0.3,1.0,0.833333,1.3,90000,4.0,0.000000,0.800000,4
...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0.562500,1999,0.1,1.0,0.000000,2.0,300000,4.0,0.333333,0.800000,5
19233,15681,0.359375,2011,0.9,1.0,0.833333,2.4,160000,4.0,0.666667,0.733333,8
19234,26108,0.359375,2010,0.4,1.0,0.166667,2.0,120000,4.0,0.000000,0.466667,4
19235,5331,0.125000,2007,0.4,1.0,0.166667,2.0,50000,4.0,0.000000,0.066667,4
19236,470,0.359375,2012,0.9,1.0,0.333333,2.4,190000,4.0,0.000000,0.933333,12

In [12]:
for col in scaling:
    df[col] = minmax_scaler.fit_transform(np.array(df[col]).reshape(-1, 1))

In [13]:
df

,Price,Manufacturer,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Color,Airbags
0,13328,0.500000,0.876543,0.4,1.0,0.333333,0.175,0.000088,6.0,0.000000,0.800000,0.7500
1,16621,0.125000,0.888889,0.4,0.0,0.833333,0.150,0.000088,6.0,0.666667,0.066667,0.5000
2,8467,0.328125,0.827160,0.3,0.0,0.833333,0.065,0.000093,4.0,1.000000,0.066667,0.1250
3,3607,0.250000,0.888889,0.4,1.0,0.333333,0.125,0.000079,4.0,0.000000,0.933333,0.0000
4,11726,0.328125,0.925926,0.3,1.0,0.833333,0.065,0.000042,4.0,0.000000,0.800000,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,0.562500,0.740741,0.1,1.0,0.000000,0.100,0.000140,4.0,0.333333,0.800000,0.3125
19233,15681,0.359375,0.888889,0.9,1.0,0.833333,0.120,0.000075,4.0,0.666667,0.733333,0.5000
19234,26108,0.359375,0.876543,0.4,1.0,0.166667,0.100,0.000056,4.0,0.000000,0.466667,0.2500
19235,5331,0.125000,0.839506,0.4,1.0,0.166667,0.100,0.000023,4.0,0.000000,0.066667,0.2500
19236,470,0.359375,0.901235,0.9,1.0,0.333333,0.120,0.000088,4.0,0.000000,0.933333,0.7500

In [14]:
def process_price(x):
#     x = float("".join([i for i in x if i.isdigit() or i == "."]))
    x = 1000 * round(x/1000)

    return x

df["Price"] = df["Price"].apply(process_price)

In [15]:
df

,Price,Manufacturer,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Color,Airbags
0,13000,0.500000,0.876543,0.4,1.0,0.333333,0.175,0.000088,6.0,0.000000,0.800000,0.7500
1,17000,0.125000,0.888889,0.4,0.0,0.833333,0.150,0.000088,6.0,0.666667,0.066667,0.5000
2,8000,0.328125,0.827160,0.3,0.0,0.833333,0.065,0.000093,4.0,1.000000,0.066667,0.1250
3,4000,0.250000,0.888889,0.4,1.0,0.333333,0.125,0.000079,4.0,0.000000,0.933333,0.0000
4,12000,0.328125,0.925926,0.3,1.0,0.833333,0.065,0.000042,4.0,0.000000,0.800000,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8000,0.562500,0.740741,0.1,1.0,0.000000,0.100,0.000140,4.0,0.333333,0.800000,0.3125
19233,16000,0.359375,0.888889,0.9,1.0,0.833333,0.120,0.000075,4.0,0.666667,0.733333,0.5000
19234,26000,0.359375,0.876543,0.4,1.0,0.166667,0.100,0.000056,4.0,0.000000,0.466667,0.2500
19235,5000,0.125000,0.839506,0.4,1.0,0.166667,0.100,0.000023,4.0,0.000000,0.066667,0.2500
19236,0,0.359375,0.901235,0.9,1.0,0.333333,0.120,0.000088,4.0,0.000000,0.933333,0.7500

In [18]:
x = np.array(df.drop("Price", axis=1))[:-5].reshape(19232//32, 32, 11)
y = np.array(df["Price"]).reshape(-1, 1)[:-5].reshape(19232//32, 32, 1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train, x_test, y_train, y_test = torch.Tensor(x_train), torch.Tensor(x_test), torch.Tensor(y_train), torch.Tensor(y_test)

In [19]:
print(x_train.shape, y_train.shape)

torch.Size([480, 32, 11]) torch.Size([480, 32, 1])

In [22]:
import torch
import torch.nn as nn
import torch.optim as optim

class DNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.block = nn.Sequential(
            nn.Linear(11, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
#             nn.Sigmoid()
                                   )
    def forward(self, x):
        return self.block(x)


loss_function = nn.L1Loss()
net = DNN()
optimizer = optim.Adam(net.parameters(), lr=0.001)


for epoch in range(10_000):
    for xx, yy in zip(x_train, y_train):
        outputs = net(xx)
        loss = loss_function(outputs, yy)
        net.zero_grad()
        loss.backward()
        optimizer.step()
    
    if epoch % 1000:
        with torch.no_grad():
            output = net(x_test)
            l = loss_function(output, y_test)
        print(f"training loss: {loss}, testing loss: {l}")

training loss: 13077.2626953125, testing loss: 11393.0390625
training loss: 12861.14453125, testing loss: 11256.1318359375
training loss: 12703.580078125, testing loss: 11068.677734375
training loss: 12154.99609375, testing loss: 10746.0224609375
training loss: 11618.7744140625, testing loss: 10263.5107421875
training loss: 11406.7724609375, testing loss: 9832.7890625

KeyboardInterrupt: